before:
  hooks:
    - go run . misc -maxmind-update-license {{.Env.MAXMIND_LICENSE_KEY}}
builds:
  - id: miaospeed
    dir: .
    binary: miaospeed
    ldflags:
      - -s -w
    tags:
      - with_gvisor
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
#  - id: miaospeed.meta
#    dir: .
#    binary: miaospeed.meta
#    ldflags:
#      - -s -w -X "main.COMMIT={{.Commit}}" -X "main.BUILDCOUNT={{.Env.BUILDCOUNT}}" -X "main.BRAND={{.Env.BRAND}}" -X "main.COMPILATIONTIME={{.Env.COMPILATIONTIME}}"
#    goos:
#      - darwin
#      - linux
#      - windows
#    hooks:
#      pre: ./build.release.hook.pre.sh
#      post: ./build.release.hook.post.sh
archives:
  - id: default
    format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
  - id: with-mmdb
    format: tar.gz
    name_template: '{{ .ProjectName }}-geodb-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - "*.mmdb"
release:
  github:
    owner: AirportR
    name: miaospeed
