name: build and releases

on:
    workflow_dispatch:
    push:
      # run only against tags
      tags:
        - '*'

jobs:
  go-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the tag
        run: echo "The tag is ${{ github.ref_name }}"

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: fix embeded
        run: |
          go env
          mkdir ./preconfigs/embeded/miaokoCA
          echo "${{ secrets.MIAOSPEED_CRT }}" > ./preconfigs/embeded/miaokoCA/miaoko.crt
          echo "${{ secrets.MIAOSPEED_KEY }}" > ./preconfigs/embeded/miaokoCA/miaoko.key
          echo "${{ secrets.MS_BUILDTOKEN }}" > ./utils/embeded/BUILDTOKEN.key
          curl -o ./engine/embeded/default_geoip.js ${{ secrets.DEFAULT_GEOIP }}
          head -n 5 ./engine/embeded/default_geoip.js

      - name: build
        run: make releases

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*
          body_path: './CHANGELOG.md'
          tag_name: ${{ github.ref_name }}
