name: docker image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version tag for the Docker image:'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Get version
        id: get_version
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
#            ${{ secrets.DOCKERHUB_USERNAME }}/miaospeed:${{ steps.get_version.outputs.version }}
#            ${{ secrets.DOCKERHUB_USERNAME }}/miaospeed:latest
          build-args: |
            MY_BUILDTOKEN=${{ secrets.MY_BUILDTOKEN }}
