name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - 'v*'
    branches:
      - build

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          cache: true
      - name: fix embeded
        run: |
          go env
          mkdir ./preconfigs/embeded/miaokoCA
          echo "${{ secrets.MIAOSPEED_CRT }}" > ./preconfigs/embeded/miaokoCA/miaoko.crt
          echo "${{ secrets.MIAOSPEED_KEY }}" > ./preconfigs/embeded/miaokoCA/miaoko.key
          echo "${{ secrets.MS_BUILDTOKEN }}" > ./utils/embeded/BUILDTOKEN.key
          echo "${{ secrets.DEFAULT_IP }}" > ./engine/embeded/default_ip.js
          echo "" > ./engine/embeded/default_geoip.js
          curl -o ./engine/embeded/default_geoip.js ${{ secrets.DEFAULT_GEOIP }}
          head -n 5 ./engine/embeded/default_geoip.js
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}